% Copyright 2019 Lukas F. Lang and Sebastian Neumayer
%
% This file is part of TBIR.
%
%    TBIR is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    TBIR is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with TBIR.  If not, see <http://www.gnu.org/licenses/>.
function ML = multilevelIdentity2d(ML, maxLevel, minLevel)
%MULTILEVELIDENTITY2D Creates multlevel versions of 2D data.
%
%   ML = MULTILEVELIDENTITY2D(ML, maxLevel, minLevel) takes a multilevel
%   cell array generated by getMultilevel and creates appropriate multilevel
%   versions by simple downsampling.
%
% Input:
%   ML          cell array generated by getMultilevel.
%   maxLevel    the level such that ML{maxLevel}.R are the original
%               measurements.
%   minLevel    the coarsest level at which measurements are generated.
%
% Output:
%   ML          cell array with measurements ML{k}.R generated for all
%               levels between minLevel and maxLevel.
%
% Note that ML{maxLevel}.R stays untouched.

for k=1:maxLevel - minLevel
    % Current level.
    level = maxLevel - k;
    
    % Select data from higher level.
    data = ML{level + 1}.R;
    
    % Resize data according to number of detectors.
    ML{level}.R = imresize(data, ML{level}.ndet, 'bilinear', 'Antialiasing', false);
end
end
